[package]
name = "docker_client_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
bollard = "0.19.4"
clap = { version = "4.5.53", features = ["derive"] }
futures-util = "0.3.31"
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread"] }
